### ISSUE TITLE
Api.lua_getglobal() is Void

### ISSUE THREAD

**Issue by NQNStudios** [kevinresol/linc_lua#3]
https://github.com/kevinresol/linc_lua/blob/63bfc77d03bb820a731ee636cdb9e545b7381589/vm/lua/Api.hx#L97

I think it should be Dynamic?

**Comment by kevinresol** [comment]
https://pgl.yoyo.org/luai/i/lua_getglobal

**Comment by NQNStudios** [comment]
Oh, so the issue might be in hxvm-lua:

https://github.com/kevinresol/hxvm-lua/blob/master/src/vm/lua/Lua.hx#L85

It returns the result of lua_getglobal(), which is a Void. Maybe it should be returning toHaxeValue() of the global that is pushed to the stack?

**Comment by kevinresol** [comment]
Yeah I think so, and may need to pop (lua_pop) it after the conversion
